### ISSUE TITLE
Launch settings on Android

### ISSUE THREAD

**Issue by saleemepoch** [nativescript-community/perms#1]
Hi,

Thanks for this contribution. Perhaps the best one around for its intended purpose. Surprised it hasn't gained much traction.

A quick question: Is there a reason why openSettings() is available for iOS only? Just wondering what the limitations are.

How would you recommend I handle "Never ask me again" on android?

Thanks

**Comment by DanielDent** [comment]
I haven't yet tested, but I think the README might be behind the plugin's capabilities.

https://github.com/breningham/nativescript-advanced-permissions/blob/master/src/core/index.android.ts#L42 is a plugin I've used before, and it contains fairly similar code to what is located at https://github.com/nativescript-community/perms/blob/master/src/permissions.android.ts#L305

**Comment by farfromrefug** [comment]
@DanielDent thanks i updated the doc!
