### ISSUE TITLE
Android — Remaining undesirable console.log

### ISSUE THREAD

**Issue by NCenerar** [nativescript-community/perms#16]
Hello !

When I debug my app on Android, I have logs from this plugin.

It's coming from this line:
https://github.com/nativescript-community/perms/blob/f0afedb76a36fe86c99fae4e4db3791c26ee3f92/src/perms/index.android.ts#L51

Could it be removed ?

Thank you.

**Comment by farfromrefug** [comment]
@NCenerar thanks for the report! it is fixed and released
