### ISSUE TITLE
iOS: openSettings doesn't work

### ISSUE THREAD

**Issue by sivo1981** [nativescript-community/perms#29]
Function openSettings doesn't work on iOS 18. Any ideas?

I have also tried with this code but no success
```
          const settingsUrl = NSURL.URLWithString(UIApplicationOpenSettingsURLString)
          if (UIApplication.sharedApplication.canOpenURL(settingsUrl)) {
            UIApplication.sharedApplication.openURL(settingsUrl)
          } else {
            console.error('Unable to open settings URL.')
          }

```

**Comment by fpaaske** [comment]
The problem is that the openURL method is deprecated. You'll need to switch to the one using a callback. I don't remember the new name but it's something like this: openURLWithCompletion

**Comment by sivo1981** [comment]
Yes you are correct. Would be great if this plugin could be updated to support this also.

`UIApplication.sharedApplication.openURLOptionsCompletionHandler(url, dataSerialize({}), null);`

**Comment by farfromrefug** [comment]
@fpaaske @sivo1981 fixed in latest version!

**Comment by sivo1981** [comment]
@farfromrefug great work!
