### ISSUE TITLE
add missing notifications UIUserNotificationType.providesAppNotificationSettings

### ISSUE THREAD

**Issue by francois-pasquier** [nativescript-community/perms#7]
### Which platform(s) does your issue occur on?
- iOS
- iOS 12+
- simulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2

### Please, tell us how to recreate the issue in as much detail as possible. 
I am trying to enable [this feature](https://i.stack.imgur.com/84LDU.jpg)
Doc: https://developer.apple.com/documentation/usernotifications/unnotificationsettings/2990404-providesappnotificationsettings?language=objc
This isn't possible as the plugin only support `Alert` `Badge` and `Sound` UIUserNotificationType.

**Comment by farfromrefug** [comment]
@francois-pasquier thanks for the report. I dont really have much time to work on this right now. You are welcome to create a PR if you need that feature
Thanks
